name: watr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  fl_chart: ^0.63.0  
  flutter:
    sdk: flutter
  flutter_gemini: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  popover: ^0.3.1
  shared_preferences: ^2.4.0
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/charge.png"